### ISSUE TITLE
Ajouter réfraction | diffraction et reflexion

### ISSUE THREAD

**Issue by BaboucheOne** [BaboucheOne/PotatoRaytracing#5]
Add refraction and diffraction.
The goal is to add theses two effects on the renderer.
We need to at first the math behind, second a way to do it by code and thrid how to implement this.

- [x] Maths behind
- [x] Way to code it
- [x] Code implementation

**Comment by TahaGhadirian** [comment]
Hi, Please give me more information ( In English), I will help you if i can, Thanks!

**Comment by BaboucheOne** [comment]
@TahaGhadirian Hello ! For the moment all issues in this repository are on pause.
I'm totaly refactoring the 'potato ray tracer' to implement mesh renderer.
But if you want to help, feel free to come back in few days(I have exams so don't have much times to work on it) when refactoring will be done !
